#ifndef RNN_DEFINES_H
#define RNN_DEFINES_H

#define RNN_THREADS_IN_BLOCK 64
#define RNN_TIME_STEPS 256
#define RNN_INPUT_SIZE 512
#define RNN_HIDDEN_SIZE 8192
#define RNN_OUTPUT_SIZE 128
#define INPUT_BATCH_SIZE (RNN_INPUT_SIZE * RNN_TIME_STEPS)
#define OUTPUT_BATCH_SIZE (RNN_OUTPUT_SIZE * RNN_TIME_STEPS)
#define HIDDEN_BATCH_SIZE (2 * RNN_HIDDEN_SIZE)
// All weight matrices concatenated
#define WEIGHTS_SIZE (RNN_HIDDEN_SIZE * RNN_HIDDEN_SIZE + RNN_HIDDEN_SIZE * RNN_INPUT_SIZE + RNN_HIDDEN_SIZE * RNN_OUTPUT_SIZE)
#define RNN_VECTORSIZE 4000

#endif // RNN_DEFINES_H