#!/bin/bash

BUILD_DIR="build"

for streamcount in 1 2
do

for (( i=1; i<=10; i++ ))
do
mpirun --mca orte_keep_fqdn_hostnames t --mca btl_tcp_if_exclude docker0,docker_gwbridge,lo,vboxnet0 -np 1 ./$BUILD_DIR/app-streams-$1 $streamcount
done


for (( i=1; i<=10; i++ ))
do
mpirun --mca orte_keep_fqdn_hostnames t --mca btl_tcp_if_exclude docker0,docker_gwbridge,lo,vboxnet0 -np 1 ./$BUILD_DIR/app-streams-$1 $streamcount : -np 1 ./$BUILD_DIR/cudampislave-$1
done

for slavecount in 1 3 7 15
do

for (( i=1; i<=10; i++ ))
do
./run-streams-$1 $slavecount $streamcount
done

done

done

