#ifndef VECMAXDIV_DEFINES_H
#define VECMAXDIV_DEFINES_H

#define VECMAXDIV_VECTORSIZE 200000000
#define VECMAXDIV_BATCH_SIZE 50000
#define VECMAXDIV_BLOCKS_IN_GRID 100
#define VECMAXDIV_THREADS_IN_BLOCK (VECMAXDIV_BATCH_SIZE / VECMAXDIV_BLOCKS_IN_GRID)

#endif // VECMAXDIV_DEFINES_H