from models import RunParameters, Experiment, ExperimentResult, MultipleRunResult, SingleRunResult
from charts import time_powercap_scatter, time_batch_size_scatter, time_number_of_nodes_bar, time_number_of_nodes_scatter
from experiments import run_experiment


if __name__ == "__main__":
    # experiments definitions
    
    # run experiments
    #run_experiment(experiment_file_name="aaaaa", experiment=collatz1, number_of_runs=1)
    
    # draw charts
    experiment_result = ExperimentResult(
        description="aaaa",
        experiment_result=[
            MultipleRunResult(
                parameters=RunParameters(
                    app_name="collatz",
                    cpu_enabled=True,
                    number_of_streams=1,
                    number_od_nodes=1,
                    batch_size=0,
                    powercap=None,
                    problem_size=0
                ),
                runs=[
                    SingleRunResult(
                        execution_duration=7,
                        energy_used=0
                    )
                ]
            ),
            MultipleRunResult(
                parameters=RunParameters(
                    app_name="collatz",
                    cpu_enabled=True,
                    number_of_streams=2,
                    number_od_nodes=1,
                    batch_size=0,
                    powercap=None,
                    problem_size=0
                ),
                runs=[
                    SingleRunResult(
                        execution_duration=5,
                        energy_used=0
                    )
                ]
            ),
            MultipleRunResult(
                parameters=RunParameters(
                    app_name="collatz",
                    cpu_enabled=False,
                    number_of_streams=1,
                    number_od_nodes=1,
                    batch_size=0,
                    powercap=None,
                    problem_size=0
                ),
                runs=[
                    SingleRunResult(
                        execution_duration=6,
                        energy_used=0
                    )
                ]
            ),
            MultipleRunResult(
                parameters=RunParameters(
                    app_name="collatz",
                    cpu_enabled=False,
                    number_of_streams=2,
                    number_od_nodes=1,
                    batch_size=0,
                    powercap=None,
                    problem_size=0
                ),
                runs=[
                    SingleRunResult(
                        execution_duration=4,
                        energy_used=0
                    )
                ]
            ),
            MultipleRunResult(
                parameters=RunParameters(
                    app_name="collatz",
                    cpu_enabled=True,
                    number_of_streams=1,
                    number_od_nodes=2,
                    batch_size=0,
                    powercap=None,
                    problem_size=0
                ),
                runs=[
                    SingleRunResult(
                        execution_duration=3,
                        energy_used=0
                    )
                ]
            ),
            MultipleRunResult(
                parameters=RunParameters(
                    app_name="collatz",
                    cpu_enabled=True,
                    number_of_streams=2,
                    number_od_nodes=2,
                    batch_size=0,
                    powercap=None,
                    problem_size=0
                ),
                runs=[
                    SingleRunResult(
                        execution_duration=5,
                        energy_used=0
                    )
                ]
            ),
            MultipleRunResult(
                parameters=RunParameters(
                    app_name="collatz",
                    cpu_enabled=False,
                    number_of_streams=1,
                    number_od_nodes=2,
                    batch_size=0,
                    powercap=None,
                    problem_size=0
                ),
                runs=[
                    SingleRunResult(
                        execution_duration=6,
                        energy_used=0
                    )
                ]
            ),
            MultipleRunResult(
                parameters=RunParameters(
                    app_name="collatz",
                    cpu_enabled=False,
                    number_of_streams=2,
                    number_od_nodes=2,
                    batch_size=0,
                    powercap=None,
                    problem_size=0
                ),
                runs=[
                    SingleRunResult(
                        execution_duration=4,
                        energy_used=0
                    )
                ]
            ),
        ]
    )
    time_number_of_nodes_bar(experiment_result=experiment_result)
    