#ifndef PATTERNSEARCH_DEFINES_H
#define PATTERNSEARCH_DEFINES_H

#define PATTERNSEARCH_THREADS_IN_BLOCK 64
#define PATTERNLENGTH 400
#define PATTERNCOUNT 400
#define PATTERNSEARCH_VECTORSIZE 960000000

#endif // PATTERNSEARCH_DEFINES_H