#ifndef PATTERNSEARCH_DEFINES_H
#define PATTERNSEARCH_DEFINES_H

#define PATTERNSEARCH_VECTORSIZE 400000000
#define PATTERNSEARCH_BLOCKS_IN_GRID 100
#define PATTERNLENGTH 400
#define PATTERNCOUNT 400

#endif // PATTERNSEARCH_DEFINES_H