#ifndef PATTERNSEARCH_DEFINES_H
#define PATTERNSEARCH_DEFINES_H

#define PATTERNSEARCH_VECTORSIZE 400000000
#define PATTERNSEARCH_BATCH_SIZE 50000
#define PATTERNSEARCH_BLOCKS_IN_GRID 100
#define PATTERNSEARCH_THREADS_IN_BLOCK (PATTERNSEARCH_BATCH_SIZE / PATTERNSEARCH_BLOCKS_IN_GRID)
#define PATTERNLENGTH 400
#define PATTERNCOUNT 400

#endif // PATTERNSEARCH_DEFINES_H